version: '3.9'
services:
  db:
      image: mysql:8.0.21
      container_name: store-db
      env_file:
        - ../.env
      platform: linux/x86_64
      ports:
        - 3002:3306
      volumes:
        - ./data:/var/lib/mysql
      restart: 'always'
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
        timeout: 10s
        retries: 5
      cap_add:
        - SYS_NICE # Deve omitir alertas menores

volumes:
  data: